version: "3.8"
services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo-db
    ports:
      - '5432:5432'
